### PR TITLE
More versatile log file discovery

### PR DESCRIPTION
**Pull request by kjoe**
Support Debian/Ubuntu and other Postgres installs.

### CODE REVIEW

**Comment by lesovsky** [comment]
You've touched a very fragile part of pgcenter)) Ideally ot should be carefully tested.
Please explain pros of you PR.

**Comment by lesovsky** [comment]
I don't like `lookupSystemLogfile()`, enumerating over list of hardcoded logfile is not a good idea. Potentially, in future versions of postgres packages (or in other Linux distributions) file name might change and this code will not work.

**Comment by kjoe** [comment]
You're right! I've added command line parameter to specify custom logpath, and optionally for logfile too.

Pros of my PR are:

1. PgVersion checks needed because pgcenter itself flood the log with "function ... does not exist" errors when searching for log file.

2. Previous log file discovery does not changed, just moved into "pgLoggingCollector" block, because PostgreSQL documentation and default config file says, that those settings are only used, when logging_collector is in effect.

3. The most important portion of this PR is supporting PostgreSQL .deb-based installs, because log file view doesn't work with these distributions. PostgreSQL filesystem layout stable at least the last 15 years in Debian Linux, as I remember: https://wiki.debian.org/PostgreSql#File_locations and supporting several running postgresql instance on same system (see pg_lsclusters).

4. Additionally try to guess the other well-known log file locations too, for the sake of completeness.

**Comment by lesovsky** [comment]
Please, create a new PR and add there the commit with cursor handling improvements.
Commit related to .gitignore will be rejected - it's not the task of the repo to store local settings of git.

**Comment by kjoe** [comment]
I'm sorry that I messed up this PR.

**Comment by lesovsky** [comment]
Sorry for unanswered PR rejection, I will try to summarize my thoughts later why it has been rejected.

**Pull request closed without merging**
